baseURL = "http://ashtonkemerling.com/"
languageCode = "en-us"
title = "Ashton Kemerling"
theme = "hugo-notepadium"
googleAnalytics = "UA-32325955-1"
enableGitInfo = true

[params]
    author = "Ashton Kemerling"
    description = "Ashton Kemerling's personal website"
    keywords = "blog,developer,personal"
    info = "Developer, manager, all around decent guy."
    avatarurl = "images/avatar.jpg"
    # footercontent = "Enter a text here."

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    featured_image = "/images/scott-trento-mUFFI4CkmAI-unsplash.jpg"

    # Use inverted colors
    inverted = false

    # Custom CSS
    custom_css = []

[taxonomies]
  series = "series"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/AshtonKem/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/ashton/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/ashton-kemerling/"

[[params.nav.custom]]
title = "About"
url = "/about/"

[[params.nav.custom]]
title = "Resume"
url = "/resume/"